sudo: required
dist: trusty

language: node_js
node_js: "7"

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd src/main/angular

script:
  - npm test -- --single-run

after_success:
    - npm run build -- --aot --prod

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run deploy -- --token=$FIREBASE_KEY
  on:
    branch: master